import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'Minh',
      email: 'hminh357@gmail.com',
      password: bcrypt.hashSync('123'),
      isAdmin: true,
    },
    {
      name: 'nah',
      email: 'nam@gmail.com',
      password: bcrypt.hashSync('123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Tshirt',
      slug: 'free-Tshirt',
      category: 'shirt',
      image: '/images/1.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInstock: 20,
      description: 'a popular tee shirt',
      isFeatured: true,
      banner: '/images/banner.jpg',
    },
    {
      name: 'Free Tshirt 2',
      slug: 'free-Tshirt2',
      category: 'shirt',
      image: '/images/2.png',
      price: 50,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 7,
      countInstock: 30,
      description: 'a  tee shirt',
      isFeatured: false,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Free Tshirt 3',
      slug: 'free-Tshirt3',
      category: 'shirt',
      image: '/images/3.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInstock: 20,
      description: 'a popular tee shirt',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    {
      name: 'Free Tshirt 4',
      slug: 'free-Tshirt4',
      category: 'shirt',
      image: '/images/4.png',
      price: 40,
      brand: 'Nike',
      rating: 5,
      numReviews: 4,
      countInstock: 70,
      description: 'a popular  shirt',
      isFeatured: true,
      banner: '/images/banner4.jpg',
    },
    {
      name: 'Free Tshirt 5',
      slug: 'free-Tshirt5',
      category: 'shirt',
      image: '/images/5.png',
      price: 70,
      brand: 'Nike',
      rating: 3,
      numReviews: 5,
      countInstock: 5,
      description: 'a popular tee shirt',
      isFeatured: true,
      banner: '/images/banner5.jpg',
    },
    {
      name: 'Free Tshirt 6',
      slug: 'free-Tshirt6',
      category: 'shirt',
      image: '/images/6.png',
      price: 5,
      brand: 'Nike',
      rating: 3.6,
      numReviews: 66,
      countInstock: 20,
      description: 'a popular tee shirt',
      isFeatured: true,
      banner: '/images/banner6.jpg',
    },
  ],
}

export default data
